### ISSUE TITLE
Docker-compose to use the network host but could not resolve tailscale network domain

### ISSUE THREAD

**Issue by hungran** [tailscale/github-action#105]
Hi, 
I've this job auth successfully with my tailscale network
on the github runner could interact, solved domain from my machine in tail net..

however, the docker-compose could not resolve the tailscale domain by magic DNS during the `docker-compose build`
is there any missing or s
```
jobs:
    image:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app: [xxx]
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v2
              with:
                oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                tags: "tag:k8s"
                version: 1.52.0
            - run: |
                tailscale status
                curl http://thit-kho-tau.tail86658.ts.net:8888
```
