### ISSUE TITLE
DNS issue when using Github Actions TailsSale 

### ISSUE THREAD

**Issue by saarw-opti** [tailscale/github-action#107]
![Screenshot 2024-01-24 at 10 47 32](https://github.com/tailscale/github-action/assets/140308068/120e9689-ef79-4383-9cb4-c90f90422f02)

I'm trying to use TailScale GitHub actions on the *latest* (I also tested different versions) version of TailScale and getting these DNS Issues.
It also happens when attempting to install it manually on the machine while it is running, 
I've tried injecting the nameserver and the search to `/etc/resolve.conf`
On the Admin console, I've defined the machine as an Ephermal and pre-approved machine.
It happens only on GitHub action machines.

Do you know if anyone can tackle this issue?
Thanks.

**Comment by saarw-opti** [comment]
I tried both the GitHub actions and the manual installation, run on ubuntu-latest, and 20-04 (seems more stable).
tried the 1.58.0 and the 1.56.0 of tailscale.

**Comment by matthewjthomas** [comment]
I was running into a lot of transient DNS resolution failures, followed this recommendation and it seems to be working a lot better: https://github.com/tailscale/github-action/issues/51#issuecomment-1497228382

**Comment by sylr** [comment]
I too encounter a lot of transient DNS errors, my deployment pipelines randomly fail like this:

```
> Run helm package ./deploy/chart \
Successfully packaged chart and saved it to: /home/runner/work/.../..../......tgz
Error: Kubernetes cluster unreachable: Get "https://xxxxx.gr7.eu-central-1.eks.amazonaws.com/version": dial tcp: lookup xxxxx.gr7.eu-central-1.eks.amazonaws.com on 127.0.0.53:53: read udp 127.0.0.1:40699->127.0.0.53:53: i/o timeout
```

It was working fine a few weeks ago, now I have to restart my deployment pipelines a lot.

**Comment by dgivens** [comment]
I saw this a while back, but it seemed to go away for a while, then it became a problem again about a week ago. We are using the standard hosted runner and the following action. When it started causing us problems last week, we added the Tailscale version based on the same @matthewjthomas referenced, issue #51. It has not made a difference.

This is our action.

```yaml
name: 'connect_tailscale'
description: 'Connects to Tailscale'
inputs:
    ts_oauth_client_id:
        description: 'TS_OAUTH_CLIENT_ID'
        required: true
    ts_oauth_secret:
        description: 'TS_OAUTH_SECRET'
        required: true
runs:
    using: 'composite'
    steps:
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
              version: 1.64.0
              oauth-client-id: ${{ inputs.TS_OAUTH_CLIENT_ID }}
              oauth-secret: ${{ inputs.TS_OAUTH_SECRET }}
              tags: tag:github
              args: --accept-routes --accept-dns
```

**Comment by tegamckinney** [comment]
We were having these intermittent failures as well when running our github actions.  We also were still seeing issues running v1.64.0 as others had mentioned.  We recently added an additional step with a timeout, arbitrarily picked at 30s and we've noticed no failures since.  While this is a small sample size of approximately 5-10 runs since the changes, all the runs have completed successfully.

Snippet from our action:
```
    - name: Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ inputs.ts-oauth-client_id }}
        oauth-secret: ${{ inputs.ts-oauth-secret }}
        version: '1.64.0'
        tags: tag:ci

    - name: Tailscale Debug
      shell: bash
      run: |
        timeout 30 cat /etc/resolv.conf
```

If we continue to have additional issues I will debug further and report back here however I believe this seems to be a setup delay issue.

**Comment by KlausVii** [comment]
We are also experiencing DNS timeouts with tailscale in our ci. Our setup
```
     - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.64.0
```
