### ISSUE TITLE
Cannot run action on Act 

### ISSUE THREAD

**Issue by PierreSnell** [tailscale/github-action#120]
I would like to use act: https://github.com/nektos/act to test my actions. 

However, at the tailscale step I got : 
`failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)`

Here is the github flow : 

```yaml
name: Pull request
on:
    pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches:
        - main

jobs:
  preview-deployment:
    if: github.event.pull_request.draft == false
    name: preview-deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json

    - name: Install Dependencies
      run: npm install

    - name: Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:bioserver

    - uses: pulumi/actions@v5
      with:
        command: preview
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

Thanks in advance ! :)

**Comment by omri-shilton** [comment]
I'm also experiencing this but not on ACT, on action runner on kubernetes self hosted.

**Comment by AMD-NICK** [comment]
Same problem

![screenshot_2024-08-28_21 23 56@2x](https://github.com/user-attachments/assets/bc135885-833f-45e3-a91f-08852c9369a7)

**Comment by Pikachews** [comment]
A workaround I found that allows me to run Tailscale using nektos/act is the following:

1. Add `nohup` to the tailscaled startup; this prevents the daemon from exiting, which I'm guessing happens if systemctl is not available; See https://github.com/Pikachews/tailscale-action, specifically https://github.com/Pikachews/tailscale-action/commit/72b6eb8850d8a3fa0c7ed8ca897b5aa877ba7bfe
2. Enable userspace networking, because `/dev/net/tun` is not present on some(?) containers; see https://tailscale.com/kb/1112/userspace-networking
```
        uses: Pikachews/tailscale-action@main
        with:
                ...(other args)
                tailscaled-args: "--tun=userspace-networking"
```
3. Use either the MagicDNS domain (e.g. `machine-name.tailnet-name.ts.net`) or the machine's Tailscale IP to connect to the machine, because `/etc/resolve.conf` won't be updated to be able to resolve the machine name.

This allowed me to successfully connect to other machines on the tailnet.
