### ISSUE TITLE
invalid value "nas1" for --exit-node; must be IP or unique node name

### ISSUE THREAD

**Issue by borecz** [tailscale/github-action#123]
I am trying to use `tailscale/github-action@v2` Github action. You can find my Github action code below

```
name: tailscale test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --reset --accept-routes --exit-node nas1
          hostname: github-action-${{ github.run_id }}
```

However, when running above action, I am getting error `invalid value "nas1" for --exit-node; must be IP or unique node name`

![image](https://github.com/tailscale/github-action/assets/57007154/f93efeb6-92f1-4416-8c28-3fc309770a93)

I can successfully run Tailscale using `nas1` as exit node when using Tailscale CLI

```
sudo tailscale up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}" --hostname "github-action-${{ github.run_id }}"
sudo tailscale up --reset --accept-routes --exit-node "nas1" --hostname "github-action-${{ github.run_id }}"
```

Could you guide me on how to debug this issue, please?

**Comment by seanmcne** [comment]
I ran into this as well, no matter what I do I cannot get the action to come up and assign an exit node so I broke it up into two different actions in the yaml file. 

Would be interesting to know if this is by-design and if so, could it be documented? 

```yaml
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENTID }}
        oauth-secret: ${{ secrets.TS_OAUTH_KEY }}
        tags: tag:ci
        version: 1.66.3
        #args: "--exit-node=nas1" #using this we get an error: must be IP or unique node name
    - name: Tailscale - ReRun Up Command To Set ExitNode to pfsense
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENTID }}
        oauth-secret: ${{ secrets.TS_OAUTH_KEY  }}
        tags: tag:ci
        args: "--exit-node=nas1"
        version: 1.66.3
```
