### ISSUE TITLE
SSH to host doesnt work due some issue in tailscale DNS

### ISSUE THREAD

**Issue by garry-t** [tailscale/github-action#149]
Today we have been experiencing DNS resolve issue to different hosts.  If you press `SSH to host..` it will report you error host may be offline, but host status is online and if you will be lucky enough second `SSH to host..` request will open ssh,  or no. 

Initially problem was detected from github actions, but as mentioned above also doesnt work from UI. 

```
  - name: Tailscale
    uses: tailscale/github-action@v2
    with:
      oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      tags: tag:ci
```
Couple days ago everything works ok. 

I cant provide any logs, because nothing to provide from end devices. 

Version: 
```
1.78.1
Linux 5.15.0-122-generic
```
