### ISSUE TITLE
Issue with Tailscale GitHub Action Failing in GitHub Actions Environment

### ISSUE THREAD

**Issue by borecz** [tailscale/github-action#152]
I am experiencing an issue with the Tailscale GitHub Action when running it in my GitHub Actions workflow. The action fails to connect to the Tailscale network, while it works perfectly when executed from my local machine.

**Workflow Configuration**
Here is the relevant part of my GitHub Actions workflow:

```
- name: Tailscale
  id: tailscale
  timeout-minutes: 6
  continue-on-error: true
  uses: tailscale/github-action@v3
  with:
    authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    args: --exit-node 100.105.212.65 --reset
    version: 1.78.1
```

**Request for Help**
I would appreciate any guidance on how to resolve this issue. Are there any known network restrictions in the GitHub Actions environment that could be affecting the Tailscale connection? Any help or suggestions would be greatly appreciated!
Thank you!
