### ISSUE TITLE
Unable to install tailscale download fails from GH

### ISSUE THREAD

**Issue by garry-t** [tailscale/github-action#158]
My config
```
    - name: Install Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: $TS_OAUTH_CLIENT_ID
        oauth-secret: $TS_OAUTH_SECRET
        tags: tag:ci
        version: 1.80.2

```

Error: 
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
Error: Process completed with exit code 92.

Tried with different versions no luck.
