### ISSUE TITLE
Setup Tailscale step taking two minutes

### ISSUE THREAD

**Issue by simonw** [tailscale/github-action#159]
Screenshot here: https://bsky.app/profile/simonwillison.net/post/3liu4ynyczs2d

**Comment by simonw** [comment]
Here's a simpler example that exhibits the same problem: https://github.com/simonw/playing-with-actions-single/blob/861ee201e0bb18a1af69d81aa66684c64b59f674/.github/workflows/tailscale-exit-node.yml

**Comment by simonw** [comment]
It's possible that removing `--exit-node-allow-lan-access=true` fixes this.

**Comment by simonw** [comment]
I'm now doubting myself a bit, I wonder if there's a bug here in GitHub Actions itself where the switch to Tailscale breaks the code that updates the live logging interface? So it appears to take two minutes when actually it's finishing faster than that. 

Need to run a few more experiments here.

**Comment by simonw** [comment]
... ran more experiments, I'm still seeing this problem.

**Comment by llimllib** [comment]
The [two-step dance in my setup](https://github.com/llimllib/nba_data/blob/31da6f880a409f06e3b516b084a860167a807695/.github/workflows/dl.yml#L18-L33) where I set it up first and then set the exit node afterwards only takes ~8 seconds; not clear if that's because of some difference in my setup or in setting the exit node after the network is up

**Comment by llimllib** [comment]
I'm now seeing the tailscale github-action setup action take 2 minutes (also the timeout for me), then report in github actions that it only took 8 seconds, which is pretty bizarre

**Comment by llimllib** [comment]
And also sometimes I'm seeing it report no output, and then a future step fails but it seems to me like the tailscale step actually failed but didn't report it successfully:

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/5be5bbac-6001-46e3-9129-8ba8ae20427b" />

[this is the action output](https://github.com/llimllib/nba_data/actions/runs/13656087139/job/38175493587) for however long it stays alive

**Comment by mulhotavares** [comment]
I see the same.
But after some more debugging it seems the connection is fast, but it messes with github internals.
What I did: I added steps before and after to compute the duration, I sent that to a file, and then in a different step (outside my composite action) I print it. You'll see the action was fast, but the composite action was hanging, and its output got lost.

**Comment by mulhotavares** [comment]
Code:
```
runs:
  using: "composite"
  steps:
      - name: print start date
        shell: bash
        run: |
          echo "Start date: $(date)"
          echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ inputs.tailscale-client-id }}
          oauth-secret: ${{ inputs.tailscale-client-secret }}
          tags: tag:github-client
          hostname: github-client-${{ github.run_id }}
          statedir: /tmp/tailscale-state/
      - name: Compute first duration
        shell: bash
        run: |
          echo "Intermediate end date: $(date)"

          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "Tailscale intermediate Duration: $DURATION seconds"

      - name: Tailscale - ReRun Up Command To Set ExitNode
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ inputs.tailscale-client-id }}
          oauth-secret: ${{ inputs.tailscale-client-secret }}
          tags: tag:github-client
          args: "--exit-node=${{ inputs.exit-node }} --exit-node-allow-lan-access"
          hostname: github-client-${{ github.run_id }}
          statedir: /tmp/tailscale-state/
      - name: Compute duration
        shell: bash
        run: |
          echo "End date: $(date)"
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "Tailscale connect Duration: $DURATION seconds" | tee -a /tmp/tailscale-duration.log

```

This composite action seems to take 2 min. But if I print the file in a step after calling it, it reports as just 10s roughtly.
