### ISSUE TITLE
Tailscale daemon causing runner to hang on teardown

### ISSUE THREAD

**Issue by DuckThom** [tailscale/github-action#163]
## Issue

When a runner is done (successful or not) while tailscaled is running, the Action hangs indefinitely untill either killed by a timeout or when a cancel action takes place.

## Workaround / Fix

For now, I've added a step in my workflow to disconnect from TS manually and kill the tailscaled process

```yaml
      - name: Teardown
        if: always()
        run: |
          sudo -E tailscale down 
          sudo -E killall tailscaled 
```
