### ISSUE TITLE
failed to connect to local tailscaled

### ISSUE THREAD

**Issue by scriptsrc** [tailscale/github-action#18]
Any idea why the action fails to connect to local `tailscaled` ? The stage then claims Success - but I'm not so sure it actually succeeded.

```
Run tailscale/github-action@v1
  with:
    authkey: ***
    version: 1.14.0
Run MINOR=$(echo $VERSION | awk -F '.' {'print $2'})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.2M  100 14.2M    0     0  13.3M      0  0:00:01  0:00:01 --:--:-- 13.3M
Run sudo tailscaled 2>~/tailscaled.log &
  sudo tailscaled 2>~/tailscaled.log &
  HOSTNAME="github-$(cat /etc/hostname)"
  until sudo tailscale up --authkey ${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} --accept-routes
  do
    sleep 0.5
  done
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TAILSCALE_AUTHKEY: ***
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
Success.
```

Here's my action.yml:
```
name: trivy scan dockerfile

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.repository }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
```
