### ISSUE TITLE
Update blog to use new github-action location

### ISSUE THREAD

**Issue by danielcompton** [tailscale/github-action#27]
https://tailscale.com/blog/2021-05-github-actions-and-tailscale/ says:

```yaml
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/tailscale-deploy-github@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.7.359
```

But the repo is now at `tailscale/github-action`. Reading the file confused me for a moment as I wasn't sure where `tailscale-deploy-github` was coming from. It might be good to update the blog post to point to the new location in the config file?
