### ISSUE TITLE
Pkgs.tailscale.com appears to be blocking Github Actions Runners

### ISSUE THREAD

**Issue by michaeldelago** [tailscale/github-action#37]
I'm experiencing an issue where it appears that `pkgs.tailscale.com` is timing out when attempting to use this action within a github workflow. In the below text box, the connection or pkgs.tailscale.com times out after 2m09s

```
  0     0    0     0    0     0      0      0 --:--:--  0:02:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (7) Failed to connect to pkgs.tailscale.com port 443: Connection timed out
```

When SSHing into the Action Runner with [tmate](https://github.com/marketplace/actions/debugging-with-tmate), the issue was verified by confirming I could `curl` an arbitrary, different domain (https://google.com was used), and then confirming that I could not `curl` the URL that would be templated with this action, https://pkgs.tailscale.com/stable/tailscale_1.24.2_amd64.tgz

Here's the steps executed within the workflow:

```yaml
- name: Get Tailscale Auth Key
  run: |
    TAILSCALE_PAYLOAD=$(curl -X POST https://api.tailscale.com/api/v2/tailnet/${{ env.TAILSCALE_NETWORK }}/keys \
      -u "${{ secrets.TAILSCALE_API_KEY }}" \
      -H "Content-Type: application/json" \
      --data-binary '{
        "capabilities": {
          "devices": {
            "create": {
              "reusable": false,
              "ephemeral": true
            }
          }
        }
      }')
    TAILSCALE_AUTH_KEY="$(jq -r '.key' <<< $TAILSCALE_PAYLOAD)"
    echo "TAILSCALE_AUTH_KEY=$TAILSCALE_AUTH_KEY" >> $GITHUB_ENV


- name: Tailscale
  uses: tailscale/github-action@v1
  with:
    authkey: "${{ env.TAILSCALE_AUTH_KEY }}"
    version: "1.24.2"
```
