### ISSUE TITLE
Network failure after tailscale connection is established

### ISSUE THREAD

**Issue by paulpet** [tailscale/github-action#39]
Sometime within the last few days (without any changes to the workflow or tailscale config) we've started seeing DNS look up failures when our Linux Ubuntu 20.04 runner is connected to tailscale. Other clients on tailscale continue to work as expected and I have confirmed that the runner establishes a connection to tailscale. I was using the v1 versions of the tailscale action, but tried using the main version with the same results. Any thoughts on how to further troubleshoot?

EDIT: After further examination (see below) it appears all network functionality breaks during a workflow once the tailscale client connects.

**Comment by paulpet** [comment]
```
  ping-pong:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Tailscale connection
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Ping
        shell: bash
        run: |
           ping -c 5 1.1.1.1
```

This will fail to even ping 1.1.1.1. 

Perhaps the Ubuntu 20.04 runner instances have been updated in some way recently by GH that is causing an issue?
