### ISSUE TITLE
Add support for Tailscale SSH

### ISSUE THREAD

**Issue by SebDanielsson** [tailscale/github-action#45]
I would love to using Tailscale SSH with this action. Would remove the need for a couple of environment variables.

**Comment by DentonGentry** [comment]
The workflow supports an `args` parameter of arguments to pass to `tailscale up`, which could be:

```
  - name: Tailscale
    uses: tailscale/github-action@v1
    with:
      authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      args: --ssh
```
