### ISSUE TITLE
DNS issue when using tailscale

### ISSUE THREAD

**Issue by asaif** [tailscale/github-action#51]
**Issue**
Github actions used tailscale with option ( DNS override activated on Admin) Failed to resolve any public DNS
like google.com for example.

**Example from a Github action**
Auth successfully on Tailscale 
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/192287/209905138-c96abab1-5606-4f05-8da1-91c2a185b894.png">

Then cannot resolve
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/192287/209906009-f9caf4e0-0f1c-417a-a16b-256d03584976.png">

**Expected behaviour** 
After connecting to tailscale Github Action runner should be able to resolve DNS without issue.

**Comment by DentonGentry** [comment]
The next step is "Set up Helm", is the runner self-hosted in Kubernetes?

**Comment by asaif** [comment]
No, it's on the normal Github runners we do install helm packages on the runner 
then use them to push our code to a private Kubernetes

**Comment by jkimbo** [comment]
I came across this issue today and setting the tailscale version to the latest one fixed it for me (for some reason it was defaulting to version `1.14.0`):

```yaml
  - name: Tailscale
    uses: tailscale/github-action@v1
    with:
      authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      version: '1.38.3'
```
