### ISSUE TITLE
`illegal base64 data at input byte 7`

### ISSUE THREAD

**Issue by selfagency** [tailscale/github-action#54]
my yaml:
```
- name: Tailscale
  uses: tailscale/github-action@v1
  with:
    authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
```

the result:
```
failed to connect to local tailscaled (which appears to be running). Got error: illegal base64 data at input byte 7
```

running on ubuntu 20
