### ISSUE TITLE
Action fails to run

### ISSUE THREAD

**Issue by shepherdjerred** [tailscale/github-action#6]
An error occurs when using this action.

Workflow failure: https://github.com/shepherdjerred/ansible-playbook/runs/3354929715?check_suite_focus=true

Workflow .yml file:
```

name: Ansible Deploy

on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        host:
          - "hades"
          - "nas"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          options: |
            --inventory production/inventory.yml
            -e@vars/vaulted_vars.yml
            --limit ${{ matrix.host }}
```

Action output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 11 14.1M   11 1632k    0     0  2105k      0  0:00:06 --:--:--  0:00:06 2103k
100 14.1M  100 14.1M    0     0  13.4M      0  0:00:01  0:00:01 --:--:-- 13.4M
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
Success.
```

Despite failing, the action succeeds and prints "Success". I'm able to see GitHub action workers in my Tailscale console.
<img width="1152" alt="Screen Shot 2021-08-17 at 2 06 47 PM" src="https://user-images.githubusercontent.com/3904778/129800703-ee16787e-1092-4ca0-961d-802d5f13c086.png">

The workflow then fails on the next step which relies on being able to connect to my Tailscale network.
