### ISSUE TITLE
Does not work on cross platform build

### ISSUE THREAD

**Issue by andrejohansson** [tailscale/github-action#61]
I might be missing something, but for me this **does not work on either linux, windows or macos** (see #56) builds.

I'm trying to cross compile a tauri app using the script published [here](https://tauri.app/v1/guides/building/cross-platform/#tauri-github-action) but all platforms fail on this action.

Since I fail on all platforms...am I missing something here? I´ve put up an epheremal key in tailscale admin console and added it to secrets.

**Action definition**

```yaml
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # Connect to our vpn in order to deliver artifacts
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
```

**macos failure**

```
Run tailscale/github-action@v1
Run MINOR=$(echo $VERSION | awk -F '.' {'print $2'})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.2M  100 14.2M    0     0  45.7M      0 --:--:-- --:--:-- --:--:-- 46.2M
mv: fastcopy: open() failed (to): /usr/bin/tailscale: Operation not permitted
mv: fastcopy: open() failed (to): /usr/bin/tailscaled: Operation not permitted
Error: Process completed with exit code 1.
```

**windows failure**

```
Run tailscale/github-action@v1
Run MINOR=$(echo $VERSION | awk -F '.' {'print $2'})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 12 14.2M   12 1888k    0     0  2659k      0  0:00:05 --:--:--  0:00:05 2662k
100 14.2M  100 14.2M    0     0  14.2M      0  0:00:01  0:00:01 --:--:-- 14.2M
D:\a\_temp\de03d6bb-0580-475e-b0c2-e60dc28bf808.sh: line 11: sudo: command not found
Error: Process completed with exit code 127.
```

**linux failure**

The tricky part with linux is that it´s reporting success but it´s actually failing.

```
Run tailscale/github-action@v1
Run MINOR=$(echo $VERSION | awk -F '.' {'print $2'})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.2M  100 14.2M    0     0   154M      0 --:--:-- --:--:-- --:--:--  154M
Run sudo tailscaled 2>~/tailscaled.log &
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
Success.
```
