### ISSUE TITLE
Seems to be spawning v1.14 & failed to connect to local tailscaled

### ISSUE THREAD

**Issue by michealroberts** [tailscale/github-action#62]
I'm seeing the following when running in a Github Action:

```
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

I'm also seeing that version 1.14 is being spawned from this action which is not playing nicely as my other networks are on v1.36 (see screenshot below).

<img width="1142" alt="Screenshot 2023-04-15 at 15 24 05" src="https://user-images.githubusercontent.com/84131395/232230413-ad4df24c-eba3-4f4a-bbcc-c7d6845d7d35.png">

Is there a way to pin a specific version?

**Comment by michealroberts** [comment]
I'm guessing it might be possible to do something like:

```
- name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_EPHEMERAL_AUTH_KEY }}
          version: "1.36.0"
```

In our ci.yml file ...
