### ISSUE TITLE
tailscale github-action scp/ssh issues

### ISSUE THREAD

**Issue by Auggie321** [tailscale/github-action#81]
hi folks,

Does there have some solutions in tailscale/github-action copying local file to remote tailscale node ?
```yaml
***
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: |
          cd build
          source variables.env
          docker build -t ${BUILD_NAME} .
          docker save ${BUILD_NAME}|gzip > demoimage$(date "+%Y%m%d-%H%M%S").tgz

      - name: add ssh key
      ***

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: ship it
        run: |
          tailscale ip -4 $MACHINE
          echo ${{ secrets.SSH_USERNAME_ROOT }}@${{ secrets.SSH_HOST }}:/tmp
          scp -i ~/.ssh/key build/*.tgz ${{ secrets.SSH_USERNAME_ROOT }}@${{ secrets.SSH_HOST }}:/tmp
***
```
if use this configuration, tailscale/github-action inner environment can't recognized remote tailscale node ip network.
and will got bellow error:
```console
100.68.105.66
***@***:/tmp
ssh: connect to host *** port 22: Connection timed out
lost connection
Error: Process completed with exit code 1.
```
i knew deploy new tailscale node need to get permission to authenticate firstly.
not sure how to set in tailscale/github-action.
Am I missing something here ?
To add to that, tag:ci is already configured in tailscale admin console acl and target tailscale node. 
thanks
