### ISSUE TITLE
Tailscale windows support

### ISSUE THREAD

**Issue by aubreyyan** [tailscale/github-action#93]
I'm getting the following error when I add tailscale to my github actions:

```
Run echo "::error title=⛔ error hint::Support Linux Only"
  echo "::error title=⛔ error hint::Support Linux Only"
  exit 1
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
```

The github workflow looks like this:

```
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ '3.8' ]

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/checkout@v3
  ```

Is my use case not supported?
